server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/whms?useUnicode=true&charcterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: YourUsername
    password: YourPassword


